/**
 * 分野タクソノミ（キーワード階層・分野タグ）の英語表示ラベル。
 *
 * 重要: ここは「表示」専用。検索/フィルタの識別子（URL の kw=, Lab.tags の値,
 * KeywordNode の keyword/label）は日本語のままが正で、変更してはいけない。
 * en ロケールのときだけ、表示の瞬間にここで日本語→英語に差し替える。
 *
 * 未収録の語は原語（日本語）にフォールバックする（enTag/enFieldLabel 参照）。
 */

/** キーワード階層ツリーの label / keyword（日本語）→ 英語表示名 */
export const KEYWORD_LABEL_EN: Record<string, string> = {
  // 物理学
  物理学: "Physics",
  基礎物理: "Fundamental Physics",
  古典物理: "Classical Physics",
  力学: "Mechanics",
  電磁気学: "Electromagnetism",
  電磁気: "Electromagnetism",
  熱力学: "Thermodynamics",
  統計力学: "Statistical Mechanics",
  現代物理: "Modern Physics",
  量子力学: "Quantum Mechanics",
  相対論: "Relativity",
  場の理論: "Field Theory",
  凝縮系物理: "Condensed Matter Physics",
  固体物理: "Solid-State Physics",
  超伝導: "Superconductivity",
  磁性: "Magnetism",
  半導体物理: "Semiconductor Physics",
  ソフトマター: "Soft Matter",
  液晶: "Liquid Crystals",
  コロイド: "Colloids",
  "素粒子・原子核・宇宙": "Particles, Nuclei & Cosmos",
  "素粒子・原子核": "Particle & Nuclear Physics",
  素粒子: "Particle Physics",
  原子核: "Nuclear Physics",
  加速器: "Accelerators",
  "天文・宇宙": "Astronomy & Cosmology",
  天文: "Astronomy",
  宇宙論: "Cosmology",
  ブラックホール: "Black Holes",
  重力波: "Gravitational Waves",
  "光学・プラズマ": "Optics & Plasma",
  光学: "Optics",
  レーザー: "Lasers",
  量子光学: "Quantum Optics",
  非線形光学: "Nonlinear Optics",
  プラズマ: "Plasma",
  核融合: "Nuclear Fusion",
  生物物理: "Biophysics",
  分子モーター: "Molecular Motors",
  "1分子計測": "Single-Molecule Measurement",
  "1分子": "Single-Molecule",

  // 化学
  化学: "Chemistry",
  物理化学: "Physical Chemistry",
  "理論・分光": "Theory & Spectroscopy",
  量子化学: "Quantum Chemistry",
  分光: "Spectroscopy",
  反応速度: "Reaction Kinetics",
  電気化学: "Electrochemistry",
  電極: "Electrodes",
  有機化学: "Organic Chemistry",
  "合成・反応": "Synthesis & Reactions",
  有機合成: "Organic Synthesis",
  不斉合成: "Asymmetric Synthesis",
  触媒: "Catalysis",
  有機反応: "Organic Reactions",
  "天然物・薬化学": "Natural Products & Medicinal Chemistry",
  天然物: "Natural Products",
  医薬化学: "Medicinal Chemistry",
  ケミカルバイオロジー: "Chemical Biology",
  "無機・錯体化学": "Inorganic & Coordination Chemistry",
  無機化学: "Inorganic Chemistry",
  配位化学: "Coordination Chemistry",
  金属錯体: "Metal Complexes",
  固体化学: "Solid-State Chemistry",
  "高分子・材料化学": "Polymer & Materials Chemistry",
  高分子: "Polymers",
  ポリマー: "Polymers",
  ナノ材料: "Nanomaterials",
  ナノ粒子: "Nanoparticles",
  ナノテク: "Nanotech",
  ナノテクノロジー: "Nanotechnology",
  分析化学: "Analytical Chemistry",
  分析手法: "Analytical Methods",
  質量分析: "Mass Spectrometry",
  クロマトグラフィー: "Chromatography",
  "構造化学・結晶学": "Structural Chemistry & Crystallography",
  構造解析: "Structure Analysis",
  構造化学: "Structural Chemistry",
  構造生物学: "Structural Biology",
  X線結晶構造: "X-ray Crystallography",
  クライオ電顕: "Cryo-EM",
  NMR: "NMR",
  生化学: "Biochemistry",
  酵素: "Enzymes",
  代謝: "Metabolism",

  // 生物学
  生物学: "Biology",
  "分子・細胞": "Molecular & Cell Biology",
  分子: "Molecules",
  DNA: "DNA",
  RNA: "RNA",
  ゲノム: "Genome",
  エピゲノム: "Epigenome",
  タンパク質: "Proteins",
  受容体: "Receptors",
  キナーゼ: "Kinases",
  脂質: "Lipids",
  糖質: "Carbohydrates",
  細胞: "Cells",
  ミトコンドリア: "Mitochondria",
  小胞体: "Endoplasmic Reticulum",
  リソソーム: "Lysosomes",
  オートファジー: "Autophagy",
  細胞分裂: "Cell Division",
  細胞周期: "Cell Cycle",
  アポトーシス: "Apoptosis",
  シグナル伝達: "Signal Transduction",
  遺伝子発現: "Gene Expression",
  遺伝子: "Genes",
  転写: "Transcription",
  翻訳: "Translation",
  エピジェネティクス: "Epigenetics",
  クロマチン: "Chromatin",
  神経科学: "Neuroscience",
  基礎神経科学: "Basic Neuroscience",
  神経: "Neurons",
  脳: "Brain",
  シナプス: "Synapses",
  神経回路: "Neural Circuits",
  神経伝達物質: "Neurotransmitters",
  イオンチャネル: "Ion Channels",
  "認知・行動": "Cognition & Behavior",
  学習: "Learning",
  記憶: "Memory",
  認知: "Cognition",
  行動: "Behavior",
  情動: "Emotion",
  "発生・モデル生物": "Development & Model Organisms",
  "発生・再生": "Development & Regeneration",
  発生: "Development",
  胚: "Embryo",
  形態形成: "Morphogenesis",
  幹細胞: "Stem Cells",
  再生: "Regeneration",
  iPS: "iPS Cells",
  モデル動物: "Model Animals",
  マウス: "Mouse",
  ゼブラフィッシュ: "Zebrafish",
  ショウジョウバエ: "Drosophila",
  線虫: "C. elegans",
  "生態・進化": "Ecology & Evolution",
  生態学: "Ecology",
  生態: "Ecology",
  群集生態: "Community Ecology",
  個体群: "Populations",
  "進化・系統": "Evolution & Phylogeny",
  進化: "Evolution",
  系統: "Phylogeny",
  分子進化: "Molecular Evolution",
  植物科学: "Plant Science",
  植物生理: "Plant Physiology",
  植物: "Plants",
  光合成: "Photosynthesis",
  シロイヌナズナ: "Arabidopsis",
  "微生物・免疫": "Microbiology & Immunology",
  微生物: "Microbes",
  細菌: "Bacteria",
  酵母: "Yeast",
  大腸菌: "E. coli",
  ウイルス: "Viruses",
  免疫学: "Immunology",
  免疫: "Immunity",
  抗体: "Antibodies",
  T細胞: "T Cells",
  炎症: "Inflammation",
  実験技術: "Lab Techniques",
  ゲノム編集: "Genome Editing",
  CRISPR: "CRISPR",
  イメージング: "Imaging",
  顕微鏡: "Microscopy",
  蛍光: "Fluorescence",
  オミクス: "Omics",
  プロテオミクス: "Proteomics",
  メタボロミクス: "Metabolomics",
  シングルセル: "Single-Cell",

  // 医学・健康科学
  "医学・健康科学": "Medicine & Health Sciences",
  がん: "Cancer",
  がん基礎: "Cancer Biology",
  腫瘍: "Tumors",
  発がん: "Carcinogenesis",
  がん進展: "Cancer Progression",
  転移: "Metastasis",
  腫瘍微小環境: "Tumor Microenvironment",
  "代謝・生活習慣病": "Metabolic & Lifestyle Diseases",
  代謝疾患: "Metabolic Disorders",
  糖尿病: "Diabetes",
  肥満: "Obesity",
  脂質代謝: "Lipid Metabolism",
  "神経・精神疾患": "Neurological & Psychiatric Disorders",
  神経変性疾患: "Neurodegenerative Diseases",
  アルツハイマー: "Alzheimer's",
  パーキンソン: "Parkinson's",
  神経変性: "Neurodegeneration",
  精神疾患: "Psychiatric Disorders",
  統合失調症: "Schizophrenia",
  うつ: "Depression",
  "循環器・呼吸器": "Cardiovascular & Respiratory",
  循環器: "Cardiovascular",
  心臓: "Heart",
  血管: "Blood Vessels",
  高血圧: "Hypertension",
  呼吸器: "Respiratory",
  肺: "Lungs",
  感染症: "Infectious Diseases",
  ウイルス感染: "Viral Infection",
  "薬学・創薬": "Pharmacy & Drug Discovery",
  薬理: "Pharmacology",
  薬物動態: "Pharmacokinetics",
  創薬: "Drug Discovery",
  薬剤設計: "Drug Design",
  公衆衛生: "Public Health",
  "疫学・予防": "Epidemiology & Prevention",
  疫学: "Epidemiology",
  予防医学: "Preventive Medicine",
  医用工学: "Biomedical Engineering",
  "医用工学・医療機器": "Biomedical Engineering & Devices",
  生体材料: "Biomaterials",
  医療機器: "Medical Devices",

  // 工学
  工学: "Engineering",
  "機械・ロボティクス": "Mechanical & Robotics",
  機械工学: "Mechanical Engineering",
  機械: "Machinery",
  制御: "Control",
  流体: "Fluids",
  ロボティクス: "Robotics",
  ロボット: "Robots",
  アクチュエータ: "Actuators",
  "電気・電子": "Electrical & Electronics",
  電子工学: "Electronics",
  半導体: "Semiconductors",
  集積回路: "Integrated Circuits",
  光デバイス: "Photonic Devices",
  通信: "Communications",
  アンテナ: "Antennas",
  信号処理: "Signal Processing",
  化学工学: "Chemical Engineering",
  "プロセス・反応": "Processes & Reactions",
  反応工学: "Reaction Engineering",
  プロセス: "Processes",
  "土木・建築": "Civil Engineering & Architecture",
  "建築・構造": "Architecture & Structures",
  建築: "Architecture",
  土木: "Civil Engineering",
  構造工学: "Structural Engineering",
  "都市・地盤": "Urban & Geotechnical",
  都市計画: "Urban Planning",
  地盤工学: "Geotechnical Engineering",
  地盤: "Geotechnics",
  交通: "Transportation",
  材料工学: "Materials Engineering",
  材料: "Materials",
  金属材料: "Metallic Materials",
  セラミックス: "Ceramics",
  複合材料: "Composites",
  薄膜: "Thin Films",
  航空宇宙: "Aerospace",
  "航空・宇宙工学": "Aeronautics & Astronautics",
  航空: "Aeronautics",
  宇宙工学: "Astronautics",
  ロケット: "Rockets",
  推進: "Propulsion",
  エネルギー: "Energy",
  エネルギー工学: "Energy Engineering",
  電池: "Batteries",
  太陽電池: "Solar Cells",
  水素: "Hydrogen",
  再生可能エネルギー: "Renewable Energy",

  // 情報工学
  情報工学: "Computing & Information",
  計算機科学: "Computer Science",
  理論計算機科学: "Theoretical CS",
  アルゴリズム: "Algorithms",
  計算量: "Computational Complexity",
  暗号: "Cryptography",
  プログラミング言語: "Programming Languages",
  システム: "Systems",
  OS: "Operating Systems",
  並列計算: "Parallel Computing",
  分散システム: "Distributed Systems",
  データベース: "Databases",
  "AI・機械学習": "AI & Machine Learning",
  機械学習: "Machine Learning",
  深層学習: "Deep Learning",
  強化学習: "Reinforcement Learning",
  "応用 AI": "Applied AI",
  自然言語処理: "NLP",
  コンピュータビジョン: "Computer Vision",
  音声認識: "Speech Recognition",
  "生成 AI": "Generative AI",
  生成AI: "Generative AI",
  データサイエンス: "Data Science",
  データ解析: "Data Analysis",
  ビッグデータ: "Big Data",
  データマイニング: "Data Mining",
  "ネットワーク・セキュリティ": "Networking & Security",
  ネットワーク: "Networking",
  IoT: "IoT",
  クラウド: "Cloud",
  セキュリティ: "Security",
  暗号通信: "Secure Communication",
  "HCI・VR": "HCI & VR",
  HCI: "HCI",
  ヒューマンインタフェース: "Human Interface",
  インタフェース: "Interfaces",
  VR: "VR",
  AR: "AR",
  バイオインフォマティクス: "Bioinformatics",
  計算生物学: "Computational Biology",
  ゲノム解析: "Genome Analysis",

  // 数学
  数学: "Mathematics",
  純粋数学: "Pure Mathematics",
  解析: "Analysis",
  微分方程式: "Differential Equations",
  関数解析: "Functional Analysis",
  "代数・幾何": "Algebra & Geometry",
  代数: "Algebra",
  幾何: "Geometry",
  トポロジー: "Topology",
  数論: "Number Theory",
  "確率・統計": "Probability & Statistics",
  "確率論・統計学": "Probability & Statistics",
  確率: "Probability",
  統計: "Statistics",
  確率過程: "Stochastic Processes",
  "応用・計算数学": "Applied & Computational Math",
  応用数学: "Applied Mathematics",
  数値解析: "Numerical Analysis",
  最適化: "Optimization",
  数理モデル: "Mathematical Modeling",

  // 地球科学・環境
  "地球科学・環境": "Earth & Environmental Science",
  地球物理: "Geophysics",
  "地震・火山": "Earthquakes & Volcanoes",
  地震: "Earthquakes",
  火山: "Volcanoes",
  地球内部: "Earth's Interior",
  "気象・気候": "Weather & Climate",
  気象: "Meteorology",
  気候変動: "Climate Change",
  大気: "Atmosphere",
  "海洋・地質": "Ocean & Geology",
  海洋: "Ocean",
  海洋生物: "Marine Biology",
  "地質・鉱物": "Geology & Minerals",
  地質: "Geology",
  鉱物: "Minerals",
  古生物: "Paleontology",
  環境科学: "Environmental Science",
  環境保全: "Environmental Conservation",
  環境: "Environment",
  生物多様性: "Biodiversity",
  持続可能: "Sustainability",
  生態系: "Ecosystems",

  // 農学
  農学: "Agriculture",
  "作物・植物科学": "Crop & Plant Science",
  作物科学: "Crop Science",
  作物: "Crops",
  育種: "Breeding",
  農芸化学: "Agricultural Chemistry",
  "畜産・獣医": "Animal Science & Veterinary",
  畜産: "Animal Husbandry",
  家畜: "Livestock",
  獣医: "Veterinary",
  "食品・水産": "Food & Fisheries",
  食品科学: "Food Science",
  食品: "Food",
  栄養: "Nutrition",
  水産: "Fisheries",
  養殖: "Aquaculture",
  "森林・林業": "Forestry",
  森林科学: "Forest Science",
  森林: "Forests",
  林業: "Forestry",
};

/**
 * OpenAlex field code (ASJC ベース) → 英語ラベル（Scopus ASJC の subject area 名に準拠）。
 * 日本語版は lib/field-labels.ts の FIELD_LABEL_BY_CODE。
 */
export const FIELD_LABEL_BY_CODE_EN: Record<string, string> = {
  "10": "Multidisciplinary",
  "11": "Agricultural & Biological Sciences",
  "12": "Arts & Humanities",
  "13": "Biochemistry, Genetics & Molecular Biology",
  "14": "Business, Management & Accounting",
  "15": "Chemical Engineering",
  "16": "Chemistry",
  "17": "Computer Science",
  "18": "Decision Sciences",
  "19": "Earth & Planetary Sciences",
  "20": "Economics, Econometrics & Finance",
  "21": "Energy",
  "22": "Engineering",
  "23": "Environmental Science",
  "24": "Immunology & Microbiology",
  "25": "Materials Science",
  "26": "Mathematics",
  "27": "Medicine",
  "28": "Neuroscience",
  "29": "Nursing",
  "30": "Pharmacology, Toxicology & Pharmaceutics",
  "31": "Physics & Astronomy",
  "32": "Psychology",
  "33": "Social Sciences",
  "34": "Veterinary",
  "35": "Dentistry",
  "36": "Health Professions",
};

import type { Locale } from "./i18n";
import { FIELD_LABEL_BY_CODE } from "./field-labels";

/** 分野タグ／キーワード（日本語）を locale に応じた表示名に。未収録は原語のまま。 */
export function localizeTag(tag: string, locale: Locale): string {
  if (locale !== "en") return tag;
  return KEYWORD_LABEL_EN[tag] ?? tag;
}

/** field code を locale に応じたラベルに。未収録/未指定は fallback。 */
export function localizeFieldLabel(
  code: string | null | undefined,
  locale: Locale,
  fallback?: string | null,
): string | null {
  if (!code) return fallback ?? null;
  const map = locale === "en" ? FIELD_LABEL_BY_CODE_EN : FIELD_LABEL_BY_CODE;
  return map[code] ?? fallback ?? null;
}
